### PR TITLE
Fix: Firebase AuthChange Propagation

### LINKED ISSUE #47: Firebase AuthChange does not propagate
The InitialSettingsProvider does not always have the correct UserId. I suspect something is wrong with the buildup logic. This occurs when starting the app as logged in user and adding a new trupp (newest feature-branch #33)

### PR DESCRIPTION
**Pull request by alina-letzien**
This pull request improves authentication handling and error safety across multiple repositories and providers. 
It also standardizes some UI code and improves robustness around initial user settings creation. 

### Occured bug
When starting the app as an already logged-in user, the InitialSettingsProvider and other repository providers did not always have the correct userId. This caused crashes or missing data when adding a new trupp, since repositories couldn't access user-specific Firestore collections.

### Root Cause
The authStateChangesProvider stream didn't emit on app startup if the user was already authenticated leaving repositories uninitialized until the next auth event.

### Key changes to fix this bug include:

**Authentication-aware repository providers and streams**
- Refactored all major repository providers (`FirefightersRepository`, `LocationsRepository`, `RadioCallRepository`, `StatusRepository`, `InitialSettingsRepository`) to return `null` when the user is not authenticated, instead of throwing or assuming a user is present. Corresponding stream providers now emit empty lists or `null` when unauthenticated, preventing crashes and simplifying consumer code. 
- Updated `InitialSettingsRepository` to require a non-null `userId` and removed internal auth guards, since validation is now handled at the provider level. 

**Initial settings creation and registration flow**
- Ensured that initial settings are created with safe defaults immediately after registration, so the app always has valid values for calculations, even if the post-registration screen is skipped. Added error handling to this process.
- In the post-registration screen, added a check to ensure the repository is available before saving initial settings, providing user feedback if authentication fails unexpectedly.

**UI and code style improvements as implemented in #43 / #44**
- Standardized use of `const` constructors and string literals.
- Minor code cleanups and type improvements, such as finalizing local variables and using clearer variable naming.

### CODE REVIEW

File: lib/repositories/initial_settings_repository.dart [hunk 1]
```diff
@@ -83,20 +75,36 @@ class InitialSettingsRepository {
...
 final initialSettingsRepositoryProvider =
-    Provider.autoDispose<InitialSettingsRepository>((ref) {
+    Provider.autoDispose<InitialSettingsRepository?>((ref) {
       final service = ref.watch(firestoreServiceProvider);
       final authState = ref.watch(authStateChangesProvider);
-      final userId = authState.value?.uid;
+      // Try to get userId from auth stream or fallback to currentUser
+      final userId = authState.maybeWhen(
+        data: (user) => user?.uid,
+        orElse: () => ref.watch(firebaseAuthServiceProvider).currentUser?.uid,
```
Comment (pbarbenheim) [inline lib/repositories/initial_settings_repository.dart]: same as firefighter repo L78

File: lib/ui/settings/settings.dart
Comment (pbarbenheim) [inline lib/ui/settings/settings.dart]: Generell question for this type of change: I get why we have to null-check there but do we give feedback to the user, that the operation was unsuccessful? Not only meant for here but in generell for these null-checks

**Review by pbarbenheim — APPROVED** [review]
👍
